In [1]:
import polars as pl
import seaborn as sns
import iggnition

## Pre-flight

In [2]:
# Load file / antibody library (paired data)
file = "./20260309_complete_database_with_lineages_and_subsets.parquet"
df = pl.read_parquet(file)

In [3]:
print(f"Total = {df.height:2,d} paired sequences")

Total = 4,840,405 paired sequences

In [4]:
# Filter out naive B cells (IgM/D with less than 1% mutation [approximated in the V gene of heavy chain])
df = df.filter(
    ~((pl.col('v_identity:0') >= 0.99) & (pl.col('c_gene:0') == 'IGHM'))
)

In [5]:
print(f"Total = {df.height:2,d} memory B cells")

Total = 2,448,194 memory B cells

In [11]:
mutated, _ = iggnition.run(df, name_col="name", wide=True, verbose=True, human_readable=False)

numbering:   0%|          | 0/4896388 [00:00<?, ? seq/s]

In [12]:
germline, _ = iggnition.run(df, paired=True, 
                            nt_col_heavy="germline:0", aa_col_heavy="germline_aa:0", 
                            nt_col_light="germline:1", aa_col_light="germline_aa:1", 
                            name_col="name", wide=True, verbose=True, human_readable=False)

numbering:   0%|          | 0/4896388 [00:00<?, ? seq/s]

## Step 1: List mutations

In [18]:
mutated

shape: (2_448_230, 892)
┌───────────────────────────┬─────┬─────┬─────┬───┬──────┬──────┬──────┬──────┐
│ seq_name                  ┆ H1  ┆ H2  ┆ H3  ┆ … ┆ L441 ┆ L442 ┆ L443 ┆ L444 │
│ ---                       ┆ --- ┆ --- ┆ --- ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ str                       ┆ u8  ┆ u8  ┆ u8  ┆   ┆ u8   ┆ u8   ┆ u8   ┆ u8   │
╞═══════════════════════════╪═════╪═════╪═════╪═══╪══════╪══════╪══════╪══════╡
│ ACGATGTTCCCTAACC_d01_w83  ┆ 71  ┆ 65  ┆ 65  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
│ TCGAGGCTCTTTCCTC_d01_w8   ┆ 67  ┆ 65  ┆ 71  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
│ GCGCAGTTCAGCTTAG_d01_w68  ┆ 67  ┆ 65  ┆ 71  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
│ GAAATGAGTGGTACAG_d01_w74  ┆ 67  ┆ 65  ┆ 71  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
│ TTTCCTCTCATGCTCC_d01_w83  ┆ 67  ┆ 65  ┆ 71  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
│ …                         ┆ …   ┆ …   ┆ …   ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
│ ATCTACTTCGACAGCC_d11_w177 ┆ 71  ┆ 65  ┆ 71  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
│ TACGGATAGAGTGAGA_d02_w187 ┆ 67  ┆ 65  ┆ 71  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
│ GGTGCGTTCACTTACT_d09_w167 ┆ 67  ┆ 65  ┆ 71  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
│ TGAGGGACAGATTGCT_d09_w184 ┆ 67  ┆ 65  ┆ 71  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
│ TTAACTCTCTGCGTAA_d11_w133 ┆ 67  ┆ 65  ┆ 71  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
└───────────────────────────┴─────┴─────┴─────┴───┴──────┴──────┴──────┴──────┘

In [14]:
germline

shape: (2_447_984, 892)
┌───────────────────────────┬─────┬─────┬─────┬───┬──────┬──────┬──────┬──────┐
│ seq_name                  ┆ H1  ┆ H2  ┆ H3  ┆ … ┆ L441 ┆ L442 ┆ L443 ┆ L444 │
│ ---                       ┆ --- ┆ --- ┆ --- ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ str                       ┆ u8  ┆ u8  ┆ u8  ┆   ┆ u8   ┆ u8   ┆ u8   ┆ u8   │
╞═══════════════════════════╪═════╪═════╪═════╪═══╪══════╪══════╪══════╪══════╡
│ ACGATGTTCCCTAACC_d01_w83  ┆ 71  ┆ 65  ┆ 65  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
│ TCGAGGCTCTTTCCTC_d01_w8   ┆ 67  ┆ 65  ┆ 71  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
│ GCGCAGTTCAGCTTAG_d01_w68  ┆ 67  ┆ 65  ┆ 71  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
│ GAAATGAGTGGTACAG_d01_w74  ┆ 67  ┆ 65  ┆ 71  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
│ TTTCCTCTCATGCTCC_d01_w83  ┆ 67  ┆ 65  ┆ 71  ┆ … ┆ 45   ┆ 45   ┆ 45   ┆ 45   │
│ …                         ┆ …   ┆ …   ┆ …   ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
│ GGGAGATTCCCTTGTG_d05_w148 ┆ 71  ┆ 65  ┆ 65  ┆ … ┆ null ┆ null ┆ null ┆ null │
│ GACGTTATCAAACCGT_d09_w107 ┆ 71  ┆ 65  ┆ 71  ┆ … ┆ null ┆ null ┆ null ┆ null │
│ CTCCTAGCAAAGTCAA_d04_w112 ┆ 67  ┆ 65  ┆ 71  ┆ … ┆ null ┆ null ┆ null ┆ null │
│ CCACCTATCTTGAGAC_d01_w78  ┆ 67  ┆ 65  ┆ 71  ┆ … ┆ null ┆ null ┆ null ┆ null │
│ GTTCGGGCAGGCGATA_d09_w167 ┆ 71  ┆ 65  ┆ 71  ┆ … ┆ null ┆ null ┆ null ┆ null │
└───────────────────────────┴─────┴─────┴─────┴───┴──────┴──────┴──────┴──────┘

In [24]:
key = "seq_name"
value_cols = [c for c in mutated.columns if c != key]

mutations = (
    mutated
    .join(germline, on=key, how="left", suffix="_2")
    .with_columns([
        (pl.col(c) - pl.col(f"{c}_2")).alias(c)
        for c in value_cols
    ])
    .select([key] + value_cols)
)

In [25]:
mutations

shape: (2_448_230, 892)
┌───────────────────────────┬──────┬──────┬──────┬───┬──────┬──────┬──────┬──────┐
│ seq_name                  ┆ H1   ┆ H2   ┆ H3   ┆ … ┆ L441 ┆ L442 ┆ L443 ┆ L444 │
│ ---                       ┆ ---  ┆ ---  ┆ ---  ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ str                       ┆ u8   ┆ u8   ┆ u8   ┆   ┆ u8   ┆ u8   ┆ u8   ┆ u8   │
╞═══════════════════════════╪══════╪══════╪══════╪═══╪══════╪══════╪══════╪══════╡
│ ACGATGTTCCCTAACC_d01_w83  ┆ 0    ┆ 0    ┆ 0    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
│ TCGAGGCTCTTTCCTC_d01_w8   ┆ 0    ┆ 0    ┆ 0    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
│ GCGCAGTTCAGCTTAG_d01_w68  ┆ 0    ┆ 0    ┆ 0    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
│ GAAATGAGTGGTACAG_d01_w74  ┆ 0    ┆ 0    ┆ 0    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
│ TTTCCTCTCATGCTCC_d01_w83  ┆ 0    ┆ 0    ┆ 0    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
│ …                         ┆ …    ┆ …    ┆ …    ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
│ ATCTACTTCGACAGCC_d11_w177 ┆ 0    ┆ 0    ┆ 0    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
│ TACGGATAGAGTGAGA_d02_w187 ┆ 0    ┆ 0    ┆ 0    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
│ GGTGCGTTCACTTACT_d09_w167 ┆ null ┆ null ┆ null ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
│ TGAGGGACAGATTGCT_d09_w184 ┆ 0    ┆ 0    ┆ 0    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
│ TTAACTCTCTGCGTAA_d11_w133 ┆ 0    ┆ 0    ┆ 0    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
└───────────────────────────┴──────┴──────┴──────┴───┴──────┴──────┴──────┴──────┘

## Step 2: Find motifs